spring:
  application:
    name: rongdada-backend-useranswer-service
  # 默认 dev 环境
  profiles:
    active: dev
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.79.19:3306/rongdada
    username: pzr
    password: 32132420010816cG
  # Redis 配置
  redis:
    database: 1
    host: 116.62.79.19
    port: 6379
    timeout: 5000
    password: redis_kTkjB3
  # 分库分表配置
  shardingsphere:
    #数据源配置
    datasource:
      # 多数据源以逗号隔开即可
      names: rongdada
      rongdada:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://116.62.79.19:3306/rongdada
        username: pzr
        password: 32132420010816cG
    # 规则配置
    rules:
      sharding:
        # 分片算法配置
        sharding-algorithms:
          # 自定义分片规则名
          answer-table-inline:
            ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
            type: INLINE
            props:
              algorithm-expression: user_answer_$->{appId % 2}
        tables:
          user_answer:
            actual-data-nodes: rongdada.user_answer_$->{0..1}
            # 分表策略
            table-strategy:
              standard:
                sharding-column: appId
                sharding-algorithm-name: answer-table-inline
server:
  address: 0.0.0.0
  port: 8105
  servlet:
    context-path: /api/userAnswer
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# AI 配置
ai:
  apiKey: 5593f8c187fa4041ad5993f8779381cb.yYnNvOEShn5ARalg
knife4j:
  enable: true

